#pragma once

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcess>
#include <QString>
#include <QStringList>

#include <cmath>
#include <iostream>
#include <string>

extern int testsPassed;
extern int testsFailed;
extern bool runFullTests;

// Trained  model path shared between test_ann.cpp and test_errors.cpp
extern QString trainedModelPath;

// clang-format off
#define CHECK(cond, msg) do { \
  if (!(cond)) { \
    std::cerr << "FAIL: " << msg << " (" << __FILE__ << ":" << __LINE__ << ")" << std::endl; \
    testsFailed++; \
  } else { \
    testsPassed++; \
  } \
} while(0)

#define CHECK_NEAR(a, b, tol, msg) CHECK(std::fabs((a) - (b)) < (tol), msg)
// clang-format on

struct ProcessResult {
    int exitCode;
    QString stdOut;
    QString stdErr;
};

// Project root: the NN-CLI source directory. Injected at compile time (NN_CLI_PROJECT_DIR)
// so fixtures and examples resolve no matter where the binary is built — e.g. a nested
// monorepo build dir like NN/build/NN-CLI/, where the old applicationDirPath()/.. heuristic
// pointed at NN/build/ instead of the source tree. Falls back to the heuristic if unset.
inline QString projectRoot()
{
#ifdef NN_CLI_PROJECT_DIR
  return QStringLiteral(NN_CLI_PROJECT_DIR);
#else
  return QCoreApplication::applicationDirPath() + "/..";
#endif
}

// Path to the NN-CLI binary (same build/ directory as test binary)
inline QString nncliPath()
{
  return QCoreApplication::applicationDirPath() + "/NN-CLI";
}

// Path to a test fixture file
inline QString fixturePath(const QString& relativePath)
{
  return projectRoot() + "/tests/fixtures/" + relativePath;
}

// Path to an example file
inline QString examplePath(const QString& relativePath)
{
  return projectRoot() + "/examples/" + relativePath;
}

// Temp directory for test outputs
inline QString tempDir()
{
  QString dir = QDir::temp().filePath("nncli_test");
  QDir().mkpath(dir);
  return dir;
}

// Clean up temp directory
inline void cleanupTemp()
{
  QDir dir(QDir::temp().filePath("nncli_test"));

  if (dir.exists())
    dir.removeRecursively();

  // Clean up test fixture outputs (auto-generated by NN-CLI during tests)
  QDir fixtureOutput(projectRoot() + "/tests/fixtures/output");

  if (fixtureOutput.exists())
    fixtureOutput.removeRecursively();
}

// Check if GPU is available by running a tiny  training on GPU
inline bool checkGPUAvailable()
{
  static int cached = -1; // -1 = not checked, 0 = no, 1 = yes

  if (cached >= 0)
    return cached == 1;

  QString modelPath = tempDir() + "/gpu_probe.nnmodel";

  QProcess process;
  process.setWorkingDirectory(QCoreApplication::applicationDirPath() + "/..");
  process.start(QCoreApplication::applicationDirPath() + "/NN-CLI",
                {"--config", projectRoot() + "/tests/fixtures/ann_train_config.json", "--mode", "train", "--device",
                 "gpu", "--samples", projectRoot() + "/tests/fixtures/ann_train_samples.json", "--output", modelPath,
                 "--log-level", "quiet"});

  if (!process.waitForStarted(5000)) {
    cached = 0;
    return false;
  }

  if (!process.waitForFinished(30000)) {
    process.kill();
    process.waitForFinished(3000);
    cached = 0;
    return false;
  }

  QFile::remove(modelPath);
  cached = (process.exitCode() == 0) ? 1 : 0;
  return cached == 1;
}

// Run NN-CLI with arguments and capture output
inline ProcessResult runNNCLI(const QStringList& args, int timeoutMs = 120000)
{
  QProcess process;
  process.setWorkingDirectory(projectRoot());
  process.start(nncliPath(), args);

  if (!process.waitForStarted(5000)) {
    return {-1, "", "Failed to start NN-CLI process"};
  }

  if (!process.waitForFinished(timeoutMs)) {
    process.kill();
    process.waitForFinished(3000);
    return {-2, "", "NN-CLI process timed out"};
  }

  return {process.exitCode(), QString::fromUtf8(process.readAllStandardOutput()),
          QString::fromUtf8(process.readAllStandardError())};
}

// Extract and parse model.json from a .nnmodel tar package, returning the JSON root object.
// Returns a null QJsonObject on failure.
inline QJsonObject readModelJsonFromPackage(const QString& packagePath)
{
  QFile file(packagePath);

  if (!file.open(QIODevice::ReadOnly)) {
    return QJsonObject();
  }

  QByteArray tarData = file.readAll();
  file.close();

  // Walk the tar archive looking for "model.json"
  const int blockSize = 512;
  int pos = 0;

  while (pos + blockSize <= tarData.size()) {
    const char* headerPtr = tarData.constData() + pos;

    // Check for end-of-archive (two zero blocks)
    if (headerPtr[0] == '\0') {
      break;
    }

    // Validate USTAR magic at offset 257
    if (qstrncmp(headerPtr + 257, "ustar", 5) != 0) {
      break;
    }

    // Parse filename from header (null-terminated, max 99 chars)
    QByteArray nameBytes(headerPtr, qstrnlen(headerPtr, 100));
    QString entryName = QString::fromUtf8(nameBytes);

    // Parse size from header (octal at offset 124, 11 octal digits)
    QByteArray sizeBytes(headerPtr + 124, 11);
    bool ok = false;
    uint entrySize = sizeBytes.toUInt(&ok, 8);

    if (!ok) {
      break;
    }

    pos += blockSize;

    // Check if this is model.json
    if (entryName == QLatin1String("model.json")) {
      QByteArray jsonData = tarData.mid(pos, static_cast<int>(entrySize));
      QJsonDocument doc = QJsonDocument::fromJson(jsonData);
      return doc.object();
    }

    // Skip data blocks (round up to 512-byte boundary)
    uint dataBlocks = (entrySize + blockSize - 1) / blockSize;
    pos += dataBlocks * blockSize;
  }

  return QJsonObject();
}
