repos:
  - repo: local
    hooks:
      - id: ensure-blank-lines
        name: ensure blank lines around if/else/try/catch
        entry: python3 scripts/ensure-blank-lines.py
        language: system
        files: '\.(cpp|hpp|h|c|cl)$'
        types: [file]

      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: '\.(cpp|hpp|h|c|cl)$'
        types: [file]

